#!/usr/bin/env perl

use strict;
use warnings;

use Term::Choose;
use File::Touch;

my $config = "$ENV{'HOME'}/.config/alacritty/alacritty.yml";
my $d = "$ENV{'HOME'}/.config/alacritty/themes/";
my $file = "$ENV{'HOME'}/.config/alacritty/themes/default.yml";

opendir(D, "$d") || die "Can't open directory $d: $!\n";
my @list = readdir(D);
my $array_ref = \@list;  
closedir(D);
 
my $new = Term::Choose->new();
 
my $choice = $new->choose( $array_ref, { alignment => 0 } ); 
my $theme = "$d$choice";

open(DATA0,"<$theme") or die "Couldn't open file $theme, $!"; 
open(DATA1,"+>$file") or die "Couldn't open file $file, $!"; 

while(<DATA0>) {
   print DATA1 $_;
}
close( DATA0 );
close( DATA1 );

touch($config);

print "Theme is set to: $theme\n"; 

#EOF
